DROP TABLE IF EXISTS BOARDGAME_PLAYER;

CREATE TABLE BOARDGAME_PLAYER(
	PLAYER_FIRST_NAME TEXT NOT NULL,
	PLAYER_LAST_NAME TEXT NOT NULL,
	CONSTRAINT uniqueVals UNIQUE (PLAYER_FIRST_NAME, PLAYER_LAST_NAME)
);